spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  redis:
    host: localhost
    port: 6379

logging.level:
  org.hibernate.SQL: debug